### PR TITLE
Python 3.9 support for master branch

### PR DESCRIPTION
**Pull request by DJATOM**

### CODE REVIEW

**Comment by DJATOM** [comment]
So updating PRs is not that difficult as I thought. Windows and Linux builds were successful, I assume everything else is OK.

**Comment by myrsloik** [comment]
I think you missed updating vsscript.cpp

**Comment by DJATOM** [comment]
In case you didn't received an update notification, I'm now posting that comment to help GitHub trigger such notification.

**Comment by OrangeChannel** [comment]
Forgot to update the docs and the windows build instructions file on the readme @DJATOM

**Pull request merged**
