### PR TITLE
Assvapour Subtitle Improvements

### PR DESCRIPTION
**Pull request by splinter98**
Two features/fixes in assvapour.Subtitle

1) Enable use of animation tags for Subtitle (such as {\fad} or {\K})
2) Enable adjusting the start and end time on the Subtitle

### CODE REVIEW

**Comment by splinter98** [comment]
That should protect against overflowing in a very rare case someone uses a crazy slow frame rate.

**Comment by myrsloik** [comment]
Would you mind updating the documentation too?

**Comment by splinter98** [comment]
No problem I will get on that.

**Comment by dubhater** [comment]
Shouldn't *end* default to numFrames - 1, for correct animations and whatnot?

**Comment by splinter98** [comment]
Because it gets converted to time and not framed, if it was numFrames-1 the last frame wouldn't have subtitle (though it may due to rounding errors)

**Comment by myrsloik** [comment]
I think splinter98 is right

**Pull request merged**
