### PR TITLE
doc: new theme, fix, cosmetics

### PR DESCRIPTION
**Pull request by soldivelot**

### CODE REVIEW

**Comment by Ichunjo** [comment]
Why did you change the theme? The old one managed the margins better and it was easier to find your way around.

**Comment by Ichunjo** [comment]
And all the R54 docs google links too are broken now

**Comment by soldivelot** [comment]
see #751

**Comment by soldivelot** [comment]
> The old one managed the margins better

be more specific, I'll adjust it with custom CSS

> it was easier to find your way around

i changed directory structure and collapse them by default to make the hierarchy clearer

> all the R54 docs google links too are broken now

you mean these?

the reason is the same as before, this problem is hard to avoid unless we leave it unchanged

**Comment by theChaosCoder** [comment]
I agree, the new theme kinda blends everything together. It's harder to read now.

**Comment by soldivelot** [comment]
i doubled left and right margins and get this

**Comment by theChaosCoder** [comment]
My complaint was about the spacing / margin between sections

In the old theme, even though it was kinda squeezed together, you still had visual block like structures which helped with reading.

image

Border applied to this theme:

image



Or with h2 margin-top 

image

I think a combination of both would improve readability
Alternative with background color https://sphinx-themes.org/sample-sites/cloud-sptheme/

**Comment by soldivelot** [comment]
my adjust:
```
.wy-nav-content {
    max-width: none;
    padding: 1.618em 4.854em;
}
h1, h2, h3, h4, h5, h6 {
    margin-top: 40px !important;
    color: #3465a4;
}
h2 {
    padding-bottom: 6px;
    border-bottom: 2px solid #3465a4;
}
h4, h5, h6 {
    font-weight: 400;
}
```
- h2: bold underline
- h3: bold
- h4-h6: regular

<pre>





</pre>

**Pull request merged**
