### PR TITLE
Improve in-repo documentation

### LINKED ISSUE #451: Add a README with documentation
https://github.com/vapoursynth/vapoursynth

The main page for this repository does not contain a `README.md` file and such does not display any documentation on GitHub.

It would be nice to at least have the first paragraph of http://www.vapoursynth.com/about/ for a short description, and say "For more information, please visit http://www.vapoursynth.com/doc/"

### PR DESCRIPTION
**Pull request by stuxcrystal**
Please squash and merge.

Fixes #451

### CODE REVIEW

**Comment by myrsloik** [comment]
Dude, I'm too cheap to buy an ssl certificate so don't litter https links everywhere

**Comment by stuxcrystal** [comment]
cPanel doesn't support Let's Encrypt. lol.

**Comment by stuxcrystal** [comment]
Fixed.

**Comment by myrsloik** [comment]
I think it's intentionally disabled to MAKE ME PAY. I'll probably switch hosting provider at some point since the current has decided to go bad.

**Comment by stuxcrystal** [comment]
Well, you gonna merge it?

**Pull request merged**
