### PR TITLE
A faster concurrent VideoNode.frames-implementation (and using that to rewrite VideoNode.output)

### PR DESCRIPTION
**Pull request by stuxcrystal**
The implementation consists of two parts:
- Reimplementing `VideoNode.frames()` render multiple frames concurrently and yielding the frames in order.
- Reimplementing `VideoNode.output()` using the reimplemented `VideoNode.frames()`-method.

This makes `VideoNode.output()` easier to implement and its performance is now solely tied to `VideoNode.frames()` which has more uses than the `output`-function itself.

### CODE REVIEW

**Comment by stuxcrystal** [comment]
Well. I think I'm done.

**Comment by stuxcrystal** [comment]
A few more bugs have been found.

**Comment by luglio** [comment]
much appreciated

**Comment by stuxcrystal** [comment]
ping

**Comment by luglio** [comment]
Minor issue in case you will concern:
```python
>>> import vapoursynth as vs
>>> src = vs.core.std.BlankClip(width=10000, height=10000)
>>> for f in src.frames():
...     pass
... 
>>> exit()
Core freed but 300480000 bytes still allocated in framebuffers
```

**Comment by myrsloik** [comment]
1. Memory leak?
2. Can you produce a version for the doodle1 branch instead?

**Comment by stuxcrystal** [comment]
I can.

**Comment by myrsloik** [comment]
Looks good. Final point to annoy you some more. I think AudioNode.frames() should get the same improvement as well. Don't even try to implement output() for it though since headers and packing is really annoying.

**Comment by stuxcrystal** [comment]
You think so? https://docs.python.org/3/library/wave.html

**Comment by myrsloik** [comment]
You still need to convert from "planar" audio to interleaved but I guess that could work.

**Comment by stuxcrystal** [comment]
Merged with #619

**Pull request closed without merging**
