### PR TITLE
Fix recent ICC addition into imwri for APiv4

### PR DESCRIPTION
**Pull request by DJATOM**

### CODE REVIEW

**Comment by myrsloik** [comment]
I can has PR without 2/3 pointless merge commits?

**Comment by DJATOM** [comment]
I will try. Probably need to nuke the branch on my end and do from scratch.

**Comment by DJATOM** [comment]
Done.

**Comment by DJATOM** [comment]
Looks like I really have to delete anything on my end and make new branch and commits, otherwise those merging commits appears.

**Comment by DJATOM** [comment]
Now I hope it's finally done.

**Pull request merged**
