### PR TITLE
Update workflows

### PR DESCRIPTION
**Pull request by HolyWu**
https://github.com/vapoursynth/vapoursynth/commit/1239124c2d70f32c468326e48bfa7e9362550c36 changed to use `std::from_chars` from C++17. Unfortunately LLVM's libc++ [does not yet implement](https://libcxx.llvm.org/Status/Cxx17.html#note-p0067) `std::from_chars for float and double`. Hence it breaks compilation on Clang/LLVM with libc++.

### CODE REVIEW

**Comment by Setsugennoao** [comment]
Why does this PR mix workflow, typos, and PresetVideoFormat?

**Comment by HolyWu** [comment]
They are meant to fix failed CI.

**Comment by Setsugennoao** [comment]
Can you also rename the struct in the docs?

**Comment by HolyWu** [comment]
I missed that. Rebased.

**Comment by myrsloik** [comment]
Will merge if you split it out into ONLY the workflow bits

**Comment by HolyWu** [comment]
Done.

**Pull request merged**
