### PR TITLE
Silence some warnings from GCC

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by sekrit-twc** [comment]
Remove all the references to NOMINMAX and define them in vcxproj files.

**Comment by Biswa96** [comment]
1. I'm not using Microsoft Visual Studio. I'm using MinGW-w64 and GCC toolchain.
2. I am not sure if removing that define breaks anything in this project.

**Comment by sekrit-twc** [comment]
You still have to fix the vcxproj files.

**Comment by Biswa96** [comment]
Is CI disabled for doodle1 branch by default? Can it be enabled?

**Comment by Biswa96** [comment]
Done.

**Comment by Biswa96** [comment]
Thank you ❤️

**Pull request merged**
