### PR TITLE
Quickfix for exotic resolutions.

### LINKED ISSUE #423: Invalid output of VideoNode.output on exotic resolutions
During testing of Yuuno 1.1, my testers reported a completely unrecognizable output when trying to encode clips with exotic resolutions.

Standard resolutions (720p, 1080p, etc.) work fine however.

Code for reproduction:

    c = core.lsmas.LWLibavSource(r"C:\Users\stuxc\Desktop\spyce.mkv")
    m = c.resize.Spline36(width=1516, height=854)[:500]
    with open('lol.y4m', 'wb') as f:
        m.output(f, y4m=True)

The video has then been encoded using the command `x264 --demuxer y4m lol.y4m -o test.mkv`. This is what happens

Windows 10 18.09 x64:
applicationframehost_2018-11-25_19-39-25

Windows 10 18.03 x64 (different User)
c7f7da

Arch Linux:
k53bc7

### PR DESCRIPTION
**Pull request by stuxcrystal**
Also: I needed more info when write fails.

### CODE REVIEW

**Comment by myrsloik** [comment]
Is this really correct? You're comparing stride(bytes) with width (pixels)

**Comment by stuxcrystal** [comment]
It should be.

This gist shows what the two cases I'm expecting:
Width and Stride do equal, and width and stride don't.
https://gist.github.com/stuxcrystal/7283658d57a1563eeef2260e99c298c2

**Comment by stuxcrystal** [comment]
Okay. Fixed that issue

**Comment by stuxcrystal** [comment]
*ping*

**Pull request merged**
