### PR TITLE
Actually use return_signature

### PR DESCRIPTION
**Pull request by stuxcrystal**
From request:
https://github.com/vapoursynth/vapoursynth/issues/602#issuecomment-664364461

### CODE REVIEW

**Comment by myrsloik** [comment]
Looks ok I guess

**Comment by myrsloik** [comment]
Did you take into consideration that the signature can be "any" for the return types? I don't see that change.

**Comment by stuxcrystal** [comment]
_construct_type defaults `typing.Any` so it shouldn't pose a problem for unknown types

**Comment by stuxcrystal** [comment]
I am however relatively sure return-types are not named.

**Pull request merged**
